spring:
  profiles:
      active: ${SPRING_PROFILES_ACTIVE}
      default: dev
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always