spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springdb
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always